#!/bin/sh
# PROTOTYPE — throwaway. One command to view HTML variants.
cd "$(dirname "$0")"
PORT="${PORT:-8766}"
echo "S7 source route — http://127.0.0.1:${PORT}/PROTOTYPE-s7-source-route.html"
echo "S8 account chrome — http://127.0.0.1:${PORT}/PROTOTYPE-s8-account-chrome.html?variant=C"
echo "Risk flow — http://127.0.0.1:${PORT}/risk-flow/PROTOTYPE-risk-flow.html?variant=detect"
echo "Old risk layout (wrong question) — http://127.0.0.1:${PORT}/PROTOTYPE-risk-layers.html?variant=A"
echo "Today one day + now — http://127.0.0.1:${PORT}/PROTOTYPE-today-one-day.html?variant=A"
echo "Notch Options planning board — http://127.0.0.1:${PORT}/PROTOTYPE-notch-options-planning.html?variant=A"
echo "Notch Options dashboard builder — http://127.0.0.1:${PORT}/PROTOTYPE-notch-options-dashboard.html?asset=usdm&board=cockpit&ticket=A&flow=A"
echo "NSE F&O on Options — http://127.0.0.1:${PORT}/PROTOTYPE-notch-options-dashboard.html?asset=options&desk=nfo&kind=opt&board=cockpit&phase=plan"
echo "Notch risk layout zoo (A/B/C, SL-only) — http://127.0.0.1:${PORT}/PROTOTYPE-notch-risk-engine.html?variant=A&asset=equity"
echo "Notch Options plot density — http://127.0.0.1:${PORT}/PROTOTYPE-notch-options-plot.html?variant=A"
echo "Notch Spot session OMS — http://127.0.0.1:${PORT}/PROTOTYPE-notch-spot-session.html?variant=A"
echo "Station desk (brokers × WWDC 26) — http://127.0.0.1:${PORT}/PROTOTYPE-station-threads.html?variant=A"
echo "Notch closed pill 1:1 — http://127.0.0.1:${PORT}/PROTOTYPE-notch-closed-pill.html?variant=A"
echo "Notch Apple HIG — http://127.0.0.1:${PORT}/PROTOTYPE-notch-hig.html?variant=A"
echo "Notch HIG × desk — http://127.0.0.1:${PORT}/PROTOTYPE-notch-desk.html?variant=A"
echo "← → or the bottom bar. Ctrl-C to stop."
python3 -m http.server "$PORT"
